Name: aicoreopsuser.rpc
ListenOn: 0.0.0.0:8081
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: aicoreopsuser.rpc
Mysql:
  Addr: "root:root@tcp(localhost:3306)/AICoreOps?charset=utf8mb4&parseTime=True&loc=Local"
MyRedis:
  Addr: 127.0.0.1:6379
JWT:
  Secret: "aicoreops"
  Expire: 15
