Name: aicoreops_api-api
Host: 0.0.0.0
Port: 8888
UserRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: aicoreopsuser.rpc
JWT:
  Secret: "aicoreops"
  Expire: 86400
MyRedis:
  Addr: 127.0.0.1:6379
