Name: aicoreops_api-api
Host: 0.0.0.0
Port: 8888
Timeout: 30000 # API 
UserRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: aicoreopsuser.rpc
ApiRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: aicoreopsrole.rpc
MenuRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: aicoreopsrole.rpc
RoleRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: aicoreopsrole.rpc
AiRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: aicoreopsai.rpc
  Timeout: 30000 # RPC
JWT:
  Secret: "aicoreops"
MyRedis:
  Addr: 127.0.0.1:6379
Casbin:
  Path: "etc/model.conf"
Mysql:
  Addr: "root:root@tcp(localhost:3306)/AICoreOps?charset=utf8mb4&parseTime=True&loc=Local"
